### ISSUE TITLE
Support for Polish (pl) Language - Hyphenation

### ISSUE THREAD

**Issue by kamack38** [typst/hypher#10]
Hi! I was wondering why Polish language hyphenation wasn't added. Unlike Romanian hyphenation, Polish has a "public" license and in the file it is called "MIT".

**Comment by laurmaedje** [comment]
I am actually unsure why it wasn't added. I have a spreadsheet on my computer specifying which patterns are included and if not, why not. It says "included", which is obviously wrong. We can add it!

**Comment by kamack38** [comment]
Thank you very much!
