### ISSUE TITLE
Support loading any/all locales individually

### ISSUE THREAD

**Issue by alexschrod** [typst/hypher#2]
It feels very anglocentric to have a dedicated feature for just the English locale.

You either get a nice, small package if all you need is the rules for English, or you have to take on the entire dataset if you want to use it with any other language, even if it's just a single other one.

**Comment by laurmaedje** [comment]
As stated in my [comment on reddit](https://www.reddit.com/r/rust/comments/w683br/comment/ihdkboc/?utm_source=share&utm_medium=web2x&context=3) my main motivation for this was simplicity. But I see how this might be cutting the wrong corner. I'll add individual features per language soon, when I find the time.
