### ISSUE TITLE
Feature `norwegian` is always mandatory

### ISSUE THREAD

**Issue by mahgoh** [typst/hypher#9]
It seems as if the Norwegian language is always mandatory if the default flags are turned off. Though, I'm not sure if I'm missing something. I had a quick look at the code, and it looks to me like the feature flag `norwegian` is only applied to `no`, but not to `nb` and `nn` in `hypher/src/lang.rs`, thus making it mandatory:

```rust
 156   #[cfg(feature = "norwegian")]
 157   b"no" => Some(Self::Norwegian),
 158   b"nb" => Some(Self::Norwegian),
 159   b"nn" => Some(Self::Norwegian),
```

I haven't tried fixing it yet, but I figure it should be an easy fix.

**Comment by laurmaedje** [comment]
Yeah, that cfg should be also on the aliases.
